### ISSUE TITLE
Wallet has bug, un-stakes the coins with no transaction log entry. 

### ISSUE THREAD

**Issue by Pizzaguy1234** [JericoinProject/JericoinCore#5]
Of 32 coins staked only received 6 coins. Stopped. The coins will appear in the transaction record, then vanish however they are in the Minting Chart on the right. Rebooting the wallet corrects the chart, but then is no record you had the coins, they will appear and disappear out of wallet total as spendable and are not in the explorer online. Gone. The value should say  'Generated but Not accepted". And it does not does not.

**Comment by TylerAnder** [comment]
Your staked coins became probably orphaned. Meaning that somebody else got them before you. The wallet and the network figured, so they disappeared from your wallet. 

If restarting clear the chart that means you did in fact not have this coins at all at the end. This is normal behavior no worries.

**Comment by Pizzaguy1234** [comment]
Missing log entry, it's a blockchain. Coins are vanishing. "generated but not accepted"

**Comment by TylerAnder** [comment]
Maybe the developer will be interested into adding a new log entry for orphaned blocks. In the meantime, you know what happened.  Closing the issue thank you

**Comment by TylerAnder** [comment]
Note tho: the code already has entries for orphaned blocks, with the specific mention of "generated but not accepted". Maybe you missed that in your log file. Nevertheless, if that can be improved to make it more obvious, the developer will look into it.
